# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171015_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='/media/default/avatar.jpg', null=True, upload_to='avatars'),
        ),
    ]
