# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20171015_1915'),
        ('reviews', '0002_auto_20171015_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewed_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.Product'),
        ),
    ]
