# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20171105_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewed_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.Product'),
        ),
    ]
