# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20171106_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='\u0423\u0434\u0430\u043b\u0438\u0442\u044c?'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=255, verbose_name='\u0422\u0435\u043a\u0441\u0442'),
        ),
    ]
