# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-27 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20171128_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='\u0423\u0434\u0430\u043b\u0438\u0442\u044c'),
        ),
    ]
