# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': '\u041a\u043e\u0440\u0437\u0438\u043d\u0430', 'verbose_name_plural': '\u041a\u043e\u0440\u0437\u0438\u043d\u044b'},
        ),
    ]
