# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_auto_20171105_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buyers',
            field=models.ManyToManyField(related_name='buy_hystory', to=settings.AUTH_USER_MODEL),
        ),
    ]
